package(default_visibility = ["//visibility:public"])

py_binary(
    name = "test_cost_client",
    srcs = ["test_cost_client.py"],
    deps = [
        "//fueling/learning/autotuner/client:cost_computation_client",
    ],
)
