package(default_visibility = ["//visibility:public"])

filegroup(
    name = "dynamic_model_dataset_train",
    srcs = [
        "117.h5",
        "118.h5",
        "119.h5",
        "120.h5",
        "122.h5",
    ],
)
