package(default_visibility = ["//visibility:public"])

py_library(
    name = "control_channel_conf",
    srcs = ["control_channel_conf.py"],
)

py_library(
    name = "open_space_planner_conf",
    srcs = ["open_space_planner_conf.py"],
)

filegroup(
    name = "profiling_conf",
    srcs = [
        "control_profiling_conf.pb.txt",
        "open_space_planner_profiling_conf.pb.txt",
        "vehicle_dynamics_profiling_conf.pb.txt",
    ],
)
