package(default_visibility = ["//visibility:public"])

py_library(
    name = "loss_utils",
    srcs = ["loss_utils.py"],
)

py_library(
    name = "network_utils",
    srcs = ["network_utils.py"],
)

py_library(
    name = "train_utils",
    srcs = ["train_utils.py"],
    deps = [
        "//fueling/common:logging",
    ]
)
