package(default_visibility = ["//visibility:public"])

py_library(
    name = "evaluation_method_util",
    srcs = ["evaluation_method_util.py"],
    deps = [
        "//fueling/common:h5_utils",
        "//fueling/common:logging",
        "//fueling/profiling/common:numpy_utils",
        "//fueling/profiling/conf:open_space_planner_conf",
        "//fueling/profiling/open_space_planner/feature_extraction:feature_extraction_utils",
    ],
)
