package(default_visibility = ["//visibility:public"])

py_library(
    name = "control_feature_visualization_utils",
    srcs = ["control_feature_visualization_utils.py"],
    deps = [
        "//fueling/common:h5_utils",
        "//fueling/common:json_utils",
        "//fueling/common:logging",
        "//fueling/common:proto_utils",
        "//fueling/profiling/conf:control_channel_conf",
        "//fueling/profiling/proto:control_profiling",
        "//fueling/profiling/proto:control_profiling_data",
    ],
)
