# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cost_computation_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

import fueling.autotuner.grpc.sim_service_pb2 as sim__service__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cost_computation_service.proto',
  package='apollo.fuelation',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1e\x63ost_computation_service.proto\x12\x10\x61pollo.fuelation\x1a\x11sim_service.proto\"\x87\x01\n\x0bModelConfig\x12\x44\n\x0cmodel_config\x18\x01 \x03(\x0b\x32..apollo.fuelation.ModelConfig.ModelConfigEntry\x1a\x32\n\x10ModelConfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"e\n\x07Request\x12+\n\x08git_info\x18\x01 \x01(\x0b\x32\x19.apollo.fuelation.GitInfo\x12-\n\x06\x63onfig\x18\x02 \x03(\x0b\x32\x1d.apollo.fuelation.ModelConfig\"8\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\x32]\n\x0f\x43ostComputation\x12J\n\x0f\x43omputeMracCost\x12\x19.apollo.fuelation.Request\x1a\x1a.apollo.fuelation.Response\"\x00\x62\x06proto3')
  ,
  dependencies=[sim__service__pb2.DESCRIPTOR,])




_MODELCONFIG_MODELCONFIGENTRY = _descriptor.Descriptor(
  name='ModelConfigEntry',
  full_name='apollo.fuelation.ModelConfig.ModelConfigEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='apollo.fuelation.ModelConfig.ModelConfigEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='apollo.fuelation.ModelConfig.ModelConfigEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=207,
)

_MODELCONFIG = _descriptor.Descriptor(
  name='ModelConfig',
  full_name='apollo.fuelation.ModelConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_config', full_name='apollo.fuelation.ModelConfig.model_config', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MODELCONFIG_MODELCONFIGENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=207,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='apollo.fuelation.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='git_info', full_name='apollo.fuelation.Request.git_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='apollo.fuelation.Request.config', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=310,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='apollo.fuelation.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='apollo.fuelation.Response.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='apollo.fuelation.Response.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='apollo.fuelation.Response.score', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=368,
)

_MODELCONFIG_MODELCONFIGENTRY.containing_type = _MODELCONFIG
_MODELCONFIG.fields_by_name['model_config'].message_type = _MODELCONFIG_MODELCONFIGENTRY
_REQUEST.fields_by_name['git_info'].message_type = sim__service__pb2._GITINFO
_REQUEST.fields_by_name['config'].message_type = _MODELCONFIG
DESCRIPTOR.message_types_by_name['ModelConfig'] = _MODELCONFIG
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelConfig = _reflection.GeneratedProtocolMessageType('ModelConfig', (_message.Message,), {

  'ModelConfigEntry' : _reflection.GeneratedProtocolMessageType('ModelConfigEntry', (_message.Message,), {
    'DESCRIPTOR' : _MODELCONFIG_MODELCONFIGENTRY,
    '__module__' : 'cost_computation_service_pb2'
    # @@protoc_insertion_point(class_scope:apollo.fuelation.ModelConfig.ModelConfigEntry)
    })
  ,
  'DESCRIPTOR' : _MODELCONFIG,
  '__module__' : 'cost_computation_service_pb2'
  # @@protoc_insertion_point(class_scope:apollo.fuelation.ModelConfig)
  })
_sym_db.RegisterMessage(ModelConfig)
_sym_db.RegisterMessage(ModelConfig.ModelConfigEntry)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'cost_computation_service_pb2'
  # @@protoc_insertion_point(class_scope:apollo.fuelation.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'cost_computation_service_pb2'
  # @@protoc_insertion_point(class_scope:apollo.fuelation.Response)
  })
_sym_db.RegisterMessage(Response)


_MODELCONFIG_MODELCONFIGENTRY._options = None

_COSTCOMPUTATION = _descriptor.ServiceDescriptor(
  name='CostComputation',
  full_name='apollo.fuelation.CostComputation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=370,
  serialized_end=463,
  methods=[
  _descriptor.MethodDescriptor(
    name='ComputeMracCost',
    full_name='apollo.fuelation.CostComputation.ComputeMracCost',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COSTCOMPUTATION)

DESCRIPTOR.services_by_name['CostComputation'] = _COSTCOMPUTATION

# @@protoc_insertion_point(module_scope)
