# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import fueling.autotuner.grpc.cost_computation_service_pb2 as cost__computation__service__pb2


class CostComputationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ComputeMracCost = channel.unary_unary(
        '/apollo.fuelation.CostComputation/ComputeMracCost',
        request_serializer=cost__computation__service__pb2.Request.SerializeToString,
        response_deserializer=cost__computation__service__pb2.Response.FromString,
        )


class CostComputationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ComputeMracCost(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CostComputationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ComputeMracCost': grpc.unary_unary_rpc_method_handler(
          servicer.ComputeMracCost,
          request_deserializer=cost__computation__service__pb2.Request.FromString,
          response_serializer=cost__computation__service__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'apollo.fuelation.CostComputation', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
