# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sim_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sim_service.proto',
  package='apollo.fuelation',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11sim_service.proto\x12\x10\x61pollo.fuelation\"\'\n\x07GitInfo\x12\x0e\n\x06\x63ommit\x18\x01 \x01(\t\x12\x0c\n\x04repo\x18\x02 \x01(\t\"\xfd\x01\n\x07JobInfo\x12+\n\x08git_info\x18\x01 \x01(\x0b\x32\x19.apollo.fuelation.GitInfo\x12\x10\n\x08scenario\x18\x02 \x01(\x05\x12@\n\x0cmodel_config\x18\x03 \x03(\x0b\x32*.apollo.fuelation.JobInfo.ModelConfigEntry\x12\x13\n\x0boutput_path\x18\x04 \x01(\t\x12\x13\n\x0boutput_file\x18\x05 \x01(\t\x12\x13\n\x0btraining_id\x18\x06 \x01(\t\x1a\x32\n\x10ModelConfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\'\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\x9b\x01\n\tAutoTuner\x12H\n\x0fTriggerBuildJob\x12\x19.apollo.fuelation.GitInfo\x1a\x18.apollo.fuelation.Status\"\x00\x12\x44\n\x0bRunScenario\x12\x19.apollo.fuelation.JobInfo\x1a\x18.apollo.fuelation.Status\"\x00\x62\x06proto3')
)




_GITINFO = _descriptor.Descriptor(
  name='GitInfo',
  full_name='apollo.fuelation.GitInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='commit', full_name='apollo.fuelation.GitInfo.commit', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repo', full_name='apollo.fuelation.GitInfo.repo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=78,
)


_JOBINFO_MODELCONFIGENTRY = _descriptor.Descriptor(
  name='ModelConfigEntry',
  full_name='apollo.fuelation.JobInfo.ModelConfigEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='apollo.fuelation.JobInfo.ModelConfigEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='apollo.fuelation.JobInfo.ModelConfigEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=334,
)

_JOBINFO = _descriptor.Descriptor(
  name='JobInfo',
  full_name='apollo.fuelation.JobInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='git_info', full_name='apollo.fuelation.JobInfo.git_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scenario', full_name='apollo.fuelation.JobInfo.scenario', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_config', full_name='apollo.fuelation.JobInfo.model_config', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_path', full_name='apollo.fuelation.JobInfo.output_path', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_file', full_name='apollo.fuelation.JobInfo.output_file', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='training_id', full_name='apollo.fuelation.JobInfo.training_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_JOBINFO_MODELCONFIGENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=334,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='apollo.fuelation.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='apollo.fuelation.Status.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='apollo.fuelation.Status.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=375,
)

_JOBINFO_MODELCONFIGENTRY.containing_type = _JOBINFO
_JOBINFO.fields_by_name['git_info'].message_type = _GITINFO
_JOBINFO.fields_by_name['model_config'].message_type = _JOBINFO_MODELCONFIGENTRY
DESCRIPTOR.message_types_by_name['GitInfo'] = _GITINFO
DESCRIPTOR.message_types_by_name['JobInfo'] = _JOBINFO
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GitInfo = _reflection.GeneratedProtocolMessageType('GitInfo', (_message.Message,), {
  'DESCRIPTOR' : _GITINFO,
  '__module__' : 'sim_service_pb2'
  # @@protoc_insertion_point(class_scope:apollo.fuelation.GitInfo)
  })
_sym_db.RegisterMessage(GitInfo)

JobInfo = _reflection.GeneratedProtocolMessageType('JobInfo', (_message.Message,), {

  'ModelConfigEntry' : _reflection.GeneratedProtocolMessageType('ModelConfigEntry', (_message.Message,), {
    'DESCRIPTOR' : _JOBINFO_MODELCONFIGENTRY,
    '__module__' : 'sim_service_pb2'
    # @@protoc_insertion_point(class_scope:apollo.fuelation.JobInfo.ModelConfigEntry)
    })
  ,
  'DESCRIPTOR' : _JOBINFO,
  '__module__' : 'sim_service_pb2'
  # @@protoc_insertion_point(class_scope:apollo.fuelation.JobInfo)
  })
_sym_db.RegisterMessage(JobInfo)
_sym_db.RegisterMessage(JobInfo.ModelConfigEntry)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'sim_service_pb2'
  # @@protoc_insertion_point(class_scope:apollo.fuelation.Status)
  })
_sym_db.RegisterMessage(Status)


_JOBINFO_MODELCONFIGENTRY._options = None

_AUTOTUNER = _descriptor.ServiceDescriptor(
  name='AutoTuner',
  full_name='apollo.fuelation.AutoTuner',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=378,
  serialized_end=533,
  methods=[
  _descriptor.MethodDescriptor(
    name='TriggerBuildJob',
    full_name='apollo.fuelation.AutoTuner.TriggerBuildJob',
    index=0,
    containing_service=None,
    input_type=_GITINFO,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RunScenario',
    full_name='apollo.fuelation.AutoTuner.RunScenario',
    index=1,
    containing_service=None,
    input_type=_JOBINFO,
    output_type=_STATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTOTUNER)

DESCRIPTOR.services_by_name['AutoTuner'] = _AUTOTUNER

# @@protoc_insertion_point(module_scope)
