package(default_visibility = ["//visibility:public"])

filegroup(
	name = "prediction_semantic_map",
	srcs = [
	    "baidudasha.png",
	    "san_mateo.png",
	    "sunnyvale_with_two_offices.png",
	    "XiaMen.png",
	    "XiongAn.png",
	],
)
