package(default_visibility = ["//visibility:public"])

filegroup(
    name = "testdata",
    srcs = [
        "//fueling/control/dynamic_model_2_0/gp_regression/testdata/train:dynamic_model_dataset_train",
        "//fueling/control/dynamic_model_2_0/gp_regression/testdata/test:dynamic_model_dataset_test",
    ],
)
