package(default_visibility = ["//visibility:public"])

load("//tools:py_proto.bzl", "py_proto")

py_proto(
    name = "calibration_table_pb2",
    src = "calibration_table.proto"
)

py_proto(
    name = "dynamic_model_evaluation_pb2",
    src = "dynamic_model_evaluation.proto"
)

py_proto(
    name = "feature_key_pb2",
    src = "feature_key.proto"
)

py_proto(
    name = "fnn_model_pb2",
    src = "fnn_model.proto"
)
