package(default_visibility = ["//visibility:public"])

proto_library(
    name = "data_pipeline_control_lib",
    srcs = [
        "feature_key.proto",
        "calibration_table.proto",
    ],
    deps = [
        "//modules/common/proto:drive_state_proto_lib",
        "//modules/common/proto:geometry_proto_lib",
        "//modules/common/proto:header_proto_lib",
        "//modules/common/proto:vehicle_signal_proto_lib",
    ],
)
