apiVersion: v1
kind: Service
metadata:
  name: costservice
  namespace: __NAMESPACE__
spec:
  selector:
    app: costservice
  ports:
   - port: 50052
     targetPort: 50052
     protocol: TCP
     name: grpc
  type: LoadBalancer
