apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: costservice-deployment
  labels:
    app: costservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: costservice
  template:
    metadata:
      labels:
        app: costservice
    spec:
      containers:
      - name: costservice
        image: __IMG__
        imagePullPolicy: Always
        command:
            - "/fuel/apps/cost_service/deploy/entrypoint.sh"
            - "__CLUSTER__"
        securityContext:
          privileged: true
        ports:
          - containerPort: 50052
      imagePullSecrets:
      - name: regsecret
---
apiVersion: v1
kind: Service
metadata:
  name: costservice
spec:
  selector:
    app: costservice
  ports:
   - port: 50052
     targetPort: 50052
     protocol: TCP
     name: grpc
