package(default_visibility = ["//visibility:public"])

py_library(
    name = "semantic_map_model",
    srcs = ["semantic_map_model.py"],
    deps = [
        "//fueling/common:coord_utils",
    ],
)
