load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "checkpoint",
    srcs = ["checkpoint.py"],
)

py_library(
    name = "common",
    srcs = ["common.py"],
)

py_library(
    name = "fastai_optim",
    srcs = ["fastai_optim.py"],
)

py_library(
    name = "learning_schedules_fastai",
    srcs = ["learning_schedules_fastai.py"],
)

py_library(
    name = "learning_schedules",
    srcs = ["learning_schedules.py"],
)

py_library(
    name = "optim",
    srcs = ["optim.py"],
)
