package(default_visibility = ["//visibility:public"])

py_binary(
    name = "convert_kinglong_to_apollo",
    srcs = ["convert_kinglong_to_apollo.py"],
    deps = [
        "//fueling/common:base_pipeline_v2",
        "//fueling/common:record_utils",
        "//fueling/common/record/kinglong/cybertron/python:convert",
    ],
)
