# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import fueling.autotuner.client.sim_service_pb2 as sim__service__pb2


class AutoTunerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.TriggerBuildJob = channel.unary_unary(
        '/apollo.fuelation.AutoTuner/TriggerBuildJob',
        request_serializer=sim__service__pb2.GitInfo.SerializeToString,
        response_deserializer=sim__service__pb2.Status.FromString,
        )
    self.RunScenario = channel.unary_unary(
        '/apollo.fuelation.AutoTuner/RunScenario',
        request_serializer=sim__service__pb2.JobInfo.SerializeToString,
        response_deserializer=sim__service__pb2.Status.FromString,
        )


class AutoTunerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def TriggerBuildJob(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RunScenario(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AutoTunerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'TriggerBuildJob': grpc.unary_unary_rpc_method_handler(
          servicer.TriggerBuildJob,
          request_deserializer=sim__service__pb2.GitInfo.FromString,
          response_serializer=sim__service__pb2.Status.SerializeToString,
      ),
      'RunScenario': grpc.unary_unary_rpc_method_handler(
          servicer.RunScenario,
          request_deserializer=sim__service__pb2.JobInfo.FromString,
          response_serializer=sim__service__pb2.Status.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'apollo.fuelation.AutoTuner', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
