package(default_visibility = ["//visibility:public"])

py_binary(
    name = "openservice_regression",
    srcs = ["openservice_regression.py"],
    deps = [
        "//fueling/common:logging",
    ],
)
