apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-endpoints
subsets:
  - addresses:
      - ip: 172.19.40.50
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 172.19.40.51
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 172.19.40.52
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 172.19.40.53
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 172.19.40.54
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 172.19.40.55
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 172.19.40.56
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 172.19.40.57
    ports:
      - port: 1
        protocol: TCP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: glusterfs-pv
  labels:
    name: glusterfs-pv
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-endpoints
    path: nfs
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glusterfs-pvc-1t
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Ti
  selector:
    matchLabels:
      name: glusterfs-pv
