package(default_visibility = ["//visibility:public"])

filegroup(
    name = "pointpillars_pretrained_model",
    srcs = [
        "voxelnet-nuscenes-58650.tckpt",
        "all.pp.mhead.cloud.config",
    ],
)
