package(default_visibility = ["//visibility:public"])

py_library(
    name = "job",
    srcs = ["job.py"],
    deps = [
        "//apps/k8s/admin_console/utils:time_utils",
        "//fueling/common:mongo_utils",
    ],
)
