apiVersion: batch/v1
kind: Job
metadata:
  name: __ROLE__-optuna-worker
  labels:
    app: optuna-worker
spec:
  parallelism: __WORKER_COUNT__
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: coworker
          image: __IMG__
          imagePullPolicy: Always
          command:
            - "/fuel/apps/optuna/deploy/optuna_entrypoint.sh"
            - "__CLUSTER__"
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STUDY_NAME
              value: __STUDY_NAME__
            - name: CONFIG_FILE
              value: __CONFIG_FILE__
            - name: WORKER_COUNT
              value: "__WORKER_COUNT__"
            - name: ROLE
              value: __ROLE__
          envFrom:
            - secretRef:
                name: postgres-secrets
            - secretRef:
                name: bos-secret
          securityContext:
            privileged: true
      imagePullSecrets:
        - name: regsecret
      restartPolicy: Never
