---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: __NAMESPACE__
type: Opaque
stringData:
  POSTGRES_PASSWORD: "apollo-autotuner!"
  POSTGRES_USER: "optuna"
  POSTGRES_DB: "optunaDatabase"
---
apiVersion: v1
kind: Service
metadata:
  name: autotune-postgres
  namespace: __NAMESPACE__
spec:
  type: LoadBalancer
  selector:
    app: autotune-postgres
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: autotune-postgres
  namespace: __NAMESPACE__
  labels:
    app: autotune-postgres
spec:
  selector:
    matchLabels:
      app: autotune-postgres
  serviceName: autotune-postgres
  template:
    metadata:
      labels:
        app: autotune-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: postgres-secrets
          ports:
            - containerPort: 5432
