package(default_visibility = ["//visibility:public"])

py_library(
    name = "dir_utils",
    srcs = ["dir_utils.py"],
    deps = [
        #TODO
    ]
)

py_library(
    name = "multi_vehicle_utils",
    srcs = ["multi_vehicle_utils.py"],
    deps = [
        #TODO
    ]
)

py_library(
    name = "sanity_check",
    srcs = ["sanity_check.py"],
    deps = [
        #TODO
    ]
)
