package(default_visibility = ["//visibility:public"])

filegroup(
    name = "conf",
    srcs = glob(["*.txt"]),
)

filegroup(
    name = "calibration_table_conf",
    srcs = ["calibration_table_conf.pb.txt"],
)
