package(default_visibility = ["//visibility:public"])

py_library(
    name = "apollo_record_reader",
    srcs = ["apollo_record_reader.py"],
    deps = [
        "@apollo//cyber/proto:record_py_pb2",
    ],
)
