package(default_visibility = ["//visibility:public"])

filegroup(
    name = "control_conf",
    srcs = [
        "no_obstacle/vehicle_param.pb.txt",
        "obstacle/vehicle_param.pb.txt",
    ],
)

filegroup(
    name = "records",
    srcs = [
        "no_obstacle/scenario522.bag",
        "obstacle/scenario569.bag",
    ],
)
