package(default_visibility = ["//visibility:public"])

filegroup(
    name = "control_conf",
    srcs = [
        "vehicle_param.pb.txt",
    ],
)

filegroup(
    name = "records",
    srcs = [
        "scenario522.bag",
    ],
)
