package(default_visibility = ["//visibility:public"])

filegroup(
    name = "control_conf",
    srcs = [
        "conf/mkz7/vehicle_param.pb.txt",
    ],
)

filegroup(
    name = "sim_test",
    srcs = [
        "sim_test/5cc1b6704504b700069ba1c7.bag",
        "sim_test/5cc1b6704504b700069ba1c8.bag",
    ],
)

filegroup(
    name = "road_test",
    srcs = [
        "road_test/Mkz7/2019-05-01/20190501110414/20190501110414.record.00001",
        "road_test/Mkz7/2019-05-01/20190501110414/20190501110414.record.00002",
        "road_test/Mkz7/vehicle_param.pb.txt",
        "road_test/Transit/2019-02-25/20190225165600/20190225165600.record",
        "road_test/Transit/vehicle_param.pb.txt",
    ],
)
