py_binary(
    name = "routing_generator",
    srcs = [
        "routing_generator.py",
    ],
    data = ["//fueling/planning/analytics:analytics"],
    deps = [
        "//fueling/common:base_pipeline",
        "//fueling/common:file_utils",
        "//fueling/common:proto_utils",
        "//fueling/common:record_utils",
    ],
)
