py_binary(
    name = "routing_generator",
    srcs = ["routing_generator.py"],
    deps = [
        "//fueling/common:base_pipeline",
        "//fueling/common:file_utils",
        "//fueling/common:proto_utils",
        "//fueling/common:record_utils",
        "@apollo//cyber/python/cyber_py3:record",
        "@planning_analytics",
    ],
)
