apiVersion: v1
kind: Service
metadata:
  name: costservice
  namespace: __NAMESPACE__
spec:
  selector:
    app: costservice
  readinessProbe:
    exec:
      command: ["/bin/grpc_health_probe", "-addr=:50052"]
    initialDelaySeconds: 60
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 5
  livenessProbe:
    exec:
      command: ["/bin/grpc_health_probe", "-addr=:50052"]
    initialDelaySeconds: 120
    periodSeconds: 60
    timeoutSeconds: 5
    failureThreshold: 5
  ports:
   - port: 50052
     targetPort: 50052
     protocol: TCP
     name: grpc
  type: LoadBalancer
