package(default_visibility = ["//visibility:public"])

# TODO: Split to single src.
filegroup(
    name = "config",
    srcs = [
        "control_cost_computation_conf.pb.txt",
        "complete_control_tuner_param_config.pb.txt",
        "lat_control_tuner_param_config.pb.txt",
        "lon_control_tuner_param_config.pb.txt",
        "mrac_tuner_param_config.pb.txt",
        "open_space_speed_tuner_param_config.pb.txt",
        "open_space_planner_cost_computation_conf.pb.txt",
    ],
)
