package(default_visibility = ["//visibility:public"])

# TODO: Split to single src.
filegroup(
    name = "config",
    srcs = [
        "mrac_tuner_param_config.pb.txt",
        "sim_scenarios.csv",
    ],
)
