---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "superSecretPassword"
  POSTGRES_USER: "optuna"
  POSTGRES_DB: "optunaDatabase"
---
apiVersion: v1
kind: Service
metadata:
  name: autotune-postgres
spec:
  type: ClusterIP
  selector:
    app: autotune-postgres
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: autotune-postgres
  labels:
    app: autotune-postgres
spec:
  selector:
    matchLabels:
      app: autotune-postgres
  serviceName: autotune-postgres
  template:
    metadata:
      labels:
        app: autotune-postgres
    spec:
      containers:
        - name: autotune-postgres
          image: apolloauto/fuel-client:20200423_1727
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: postgres-secrets
          ports:
            - containerPort: 5432
---
apiVersion: batch/v1
kind: Job
metadata:
  name: autotune-worker
spec:
  parallelism: 5
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-database
          image: apolloauto/fuel-client:20200423_1727
          imagePullPolicy: IfNotPresent
          command:
          - /bin/sh
          - -c
          - -e
          - -x
          - |
            until pg_isready -U $(POSTGRES_USER) -h postgres -p 5432;
            do echo "waiting for postgres"; sleep 2; done;
          envFrom:
            - secretRef:
                name: postgres-secrets
      containers:
        - name: worker
          image: apolloauto/fuel-client:20200423_1727
          imagePullPolicy: IfNotPresent
          command:
            - bazel run //fueling/learning/autotuner/tuner:optuna_tuner -- --cost_computation_service_url=180.76.242.157:50052 --tuner_param_config_filename=/fuel/fueling/learning/autotuner/config/mrac_tuner_param_config.pb.txt
          envFrom:
            - secretRef:
                name: postgres-secrets
---
