package(default_visibility = ["//visibility:public"])

load("//tools:py_proto.bzl", "py_proto")

py_proto(
    name = "afs_data_service_pb2",
    src = "afs_data_service.proto",
    with_grpc = True,
)
