package(default_visibility = ["//visibility:public"])

py_library(
    name = "scenario_extraction",
    srcs = ["scenario_extraction.py"],
    deps = [
        "//fueling/common:base_pipeline",
        "//fueling/common:record_utils",
    ],
)
