package(default_visibility = ["//visibility:public"])

py_library(
    name = "label_generator",
    srcs = ["label_generator.py"],
    deps = [
        "//fueling/common:logging",
        "//fueling/common:proto_utils",
    ],
)
