package(default_visibility = ["//visibility:public"])

py_library(
    name = "output_pipeline",
    srcs = ["output_pipeline.py"],
    deps = [
        "//fueling/common:base_pipeline",
        "//fueling/common:logging",
        "//fueling/common:record_utils",
        "//learning_algorithms/planning/data_preprocessing/label_generation:label_generator",
    ],
)
