name: py27
dependencies:
  - python = 2.7
  - pyspark = 2.4.0

  # Google infra
    # Known bug for higher versions.
  - gflags = 2.2.0
  - glog = 0.3.5
  - protobuf

  # Data science
  - boto3
  - h5py = 2.3.0
    # Known bug for different versions.
  - numpy = 1.8.2

  # Other.
  - pip:
    - pylint
    - pyspark-utils >= 1.2.1
