package(default_visibility = ["//visibility:public"])

py_library(
    name = "feature_extraction_utils",
    srcs = ["feature_extraction_utils.py"],
    deps = [
        "//fueling/common:logging",
        "//fueling/common:proto_utils",
        "//fueling/profiling/proto:open_space_planner_profiling_pb2",
    ],
)
