package(default_visibility = ["//visibility:public"])

py_library(
    name = "pwd_utils",
    srcs = ["pwd_utils.py"],
    data = ["//apps/k8s/admin_console:resource"],
)

py_library(
    name = "time_utils",
    srcs = ["time_utils.py"],
    data = ["//apps/k8s/admin_console:resource"],
)
