package(default_visibility = ["//visibility:public"])

py_library(
    name = "vehicle_dynamics_feature_extraction_utils",
    srcs = ["vehicle_dynamics_feature_extraction_utils.py"],
    deps = [
        "//fueling/common:logging",
        "//fueling/common:proto_utils",
        "//fueling/common:record_utils",
        "//fueling/profiling/conf:control_channel_conf",
        "//fueling/profiling/proto:control_profiling_pb2",
    ],
)
