package(default_visibility = ["//visibility:public"])

filegroup(
    name = "golden_set_data",
    srcs = [
        "20190430115905.record.00000.recover_features.npy",
        "DM10_results.npy",
        "DM20_results.npy",
    ],
)
