name: fuel
dependencies:
  - python = 3.6     # Align with Ubuntu 18.04 default.
  - pip
  - pyspark = 2.4.4  # Align with pre-built server image.

  - absl-py
  - boto3
  - matplotlib
  - numpy
  - pymongo
  - requests

  - pip:
    - pyspark-utils
