load("//tools:py_proto.bzl", "py_proto")

package(default_visibility = ["//visibility:public"])

py_proto(
    name = "control_profiling_data_pb2",
    src = "control_profiling_data.proto",
)

py_proto(
    name = "open_space_planner_profiling_pb2",
    src = "open_space_planner_profiling.proto",
)

py_proto(
    name = "control_profiling_pb2",
    src = "control_profiling.proto",
)
