package(default_visibility = ["//visibility:public"])

py_library(
    name = "filter",
    srcs = ["filter.py"],
    data = ["//apps/k8s/admin_console:resource"],
    deps = [
        "//apps/k8s/admin_console:application",
    ],
)

py_library(
    name = "paginator",
    srcs = ["paginator.py"],
    data = ["//apps/k8s/admin_console:resource"],
)
