load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "metrics",
    srcs = ["metrics.py"],
)

py_library(
    name = "tools",
    srcs = ["tools.py"],
)
