package(default_visibility = ["//visibility:public"])

py_library(
    name = "vehicle_dynamics_feature_visualization_utils",
    srcs = ["vehicle_dynamics_feature_visualization_utils.py"],
    deps = [
        "//fueling/common:logging",
        "//fueling/profiling/conf:control_channel_conf",
    ],
)
