package(default_visibility = ["//visibility:public"])

load("@default_deps//:requirements.bzl", "requirement")

py_library(
    name = "control_feature_extration_utils",
    srcs = ["control_feature_extration_utils.py"],
    deps = [
        "//fueling/common/logging",
    ]
)

